---
# Install PostgreSQL

- name: Install PostgreSQL server
  package:
    name: "{{ postgresql_server_package }}"
    state: present

- name: Install PostgreSQL contrib
  package:
    name: "{{ postgresql_contrib_package }}"
    state: present

- name: Run initdb
  command: /bin/postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/initdb.log
  when: ansible_distribution == "CentOS"

- name: Start the PostgreSQL service
  service:
    name: "postgresql"
    enabled: true
    state: started
