---
# Install Nginx

- name: Install apt-transport-https [Debian/Ubuntu]
  package:
    name: apt-transport-https
    state: present
  when: ansible_os_family == "Debian"

- name: Add Nginx gpg key [CentOS]
  rpm_key:
    state: present
    key: https://nginx.org/keys/nginx_signing.key
  when: ansible_distribution == "CentOS"

- name: Add Nginx gpg key [Debian/Ubuntu]
  apt_key:
    state: present
    url: https://nginx.org/keys/nginx_signing.key
  when: ansible_os_family == "Debian"

- name: Add Nginx repository configuration [CentOS]
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    backup: no
    mode: 0444
    owner: root
    group: root
  when: ansible_distribution == "CentOS"

- name: Add Nginx repository configuration [Debian/Ubuntu]
  template:
    src: nginx.list
    dest: /etc/apt/sources.list.d/nginx.list
    backup: no
    mode: 0444
    owner: root
    group: root
  notify: update apt cache
  when: ansible_os_family == "Debian"

- name: Copy Apt preferences file for Nginx repositories [Debian/Ubuntu]
  copy:
    src: nginx.pref
    dest: /etc/apt/preferences.d/nginx.pref
    backup: no
    mode: 0444
    owner: root
    group: root
  notify: update apt cache
  when: ansible_os_family == "Debian"

- name: Run handlers to update package manager caches
  meta: flush_handlers

- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Delete default config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx

- name: Start nginx
  service:
    name: nginx
    enabled: yes
    state: started
