---

- name: cp rsyslog.conf /etc/
  copy: 
    src: "{{ ansible_distribution }}/rsyslog.conf"
    dest: "/etc/"
  register: reconfigured
  tags: rsyslog

# We restart here instead of a handler, because we need the syslog changes
# to take effect immediately, instead of waiting for the end of the play to
# run. This makes the biggest difference when running the entire playbook
# for a new instance
- name: restart rsyslog
  service:
    name: rsyslog 
    state: restarted
  when: reconfigured.changed
  tags: rsyslog
