---
#
# So we don't go rebooting all willy-nilly, you have to pass
# -e really_reboot=True to ansible to get the reboots to run
#

# look for an explicit reboot-required from apt/deb, or any outdated libs
- name: Look for reasons to reboot
  shell: "test -e /var/run/reboot-required || grep -q '/lib[0-9]*/.* (deleted)$' /proc/*/maps && echo REBOOT"
  register: reboot_required
  failed_when: False
  changed_when: reboot_required.stdout == 'REBOOT'
  tags: really-reboot

# Reboot; see https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
# esp. the comments
- name: reboot
  # sleep gives async task time to kick off
  shell: 'sleep 2 && shutdown -r now "ansible: reboot-required detected; restarting"'
  async: 5
  # poll 0 means "fire and forget"
  poll: 0
  register: reboot
  when: really_reboot and not reboot_required is skipped and reboot_required.changed
  tags: really-reboot

- name: wait for restart
  local_action: wait_for
    host={{ ansible_host }}
    port=22
    delay=15
    timeout=300
  become: no
  when: not reboot is skipped
  tags: really-reboot
